language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.10.0'
script:
  - npm run build
  - npm test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
